# Generated by Django 3.2.18 on 2025-05-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20250427_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='boxes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='stems_per_box',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_per_stem',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='stems',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
