# Generated by Django 3.2.18 on 2025-05-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20250509_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
