# Generated by Django 3.2.18 on 2025-05-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0005_order_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='boxes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_per_stem',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stems',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stems_per_box',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes', models.PositiveIntegerField(default=1)),
                ('stems_per_box', models.PositiveIntegerField(default=1)),
                ('stems', models.PositiveIntegerField(editable=False)),
                ('price_per_stem', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
