# Generated by Django 3.2.18 on 2025-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20250529_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('original', 'Original'), ('edited', 'Edited'), ('claim', 'Claim (Bad Produce)')], default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
