# Generated by Django 3.2.18 on 2025-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('claim', 'Claim (Bad Produce)'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
