# Generated by Django 3.2.18 on 2025-08-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stem_length_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Stem length in centimeters', null=True),
        ),
        migrations.CreateModel(
            name='CustomerOrderDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem_length_cm', models.PositiveIntegerField(help_text='Default stem length in centimeters')),
                ('price_per_stem', models.DecimalField(decimal_places=2, help_text='Default price per stem', max_digits=10)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_defaults', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_defaults', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Customer order defaults',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
