# Generated by Django 3.2.7 on 2025-08-12 00:29

from django.db import migrations

def populate_order_item_stem_lengths(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')

    # Set default stem length for order items
    for item in OrderItem.objects.filter(stem_length_cm__isnull=True):
        item.stem_length_cm = 50  # Default 50cm
        item.save()

def reverse_populate_order_item_stem_lengths(apps, schema_editor):
    # No reverse operation needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20250812_0017'),
    ]

    operations = [
        migrations.RunPython(populate_order_item_stem_lengths, reverse_populate_order_item_stem_lengths),
    ]
