# Generated by Django 3.2.7 on 2025-08-12 00:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20250812_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='stem_length_cm',
            field=models.PositiveIntegerField(help_text='Stem length in centimeters'),
        ),
    ]
