# Generated by Django 3.2.18 on 2025-08-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20250812_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, help_text='Delivery status (e.g., In Transit, Delivered, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of logistics/shipping', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_provider',
            field=models.CharField(blank=True, help_text='Logistics provider name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for the shipment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_stem',
            field=models.DecimalField(decimal_places=2, help_text='Price per stem (auto-filled from customer pricing if available)', max_digits=10),
        ),
    ]
