# Generated by Django 3.2.18 on 2025-12-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20250812_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claim_status',
            field=models.CharField(blank=True, choices=[('partial_claim', 'Partial Claim'), ('full_claim', 'Full Claim')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
