# Generated by Django 3.2.18 on 2026-01-16 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20251226_1810'),
        ('products', '0004_auto_20250812_0030'),
        ('orders', '0014_auto_20251226_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of the missed sale request')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('out_of_stock', 'Out of Stock'), ('not_in_production', 'Not in Production'), ('other', 'Other')], default='out_of_stock', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional details about the request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_sales', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_sales', to='products.product')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='missedsale',
            index=models.Index(fields=['date'], name='orders_miss_date_40752b_idx'),
        ),
        migrations.AddIndex(
            model_name='missedsale',
            index=models.Index(fields=['reason'], name='orders_miss_reason_44bc39_idx'),
        ),
    ]
