# Generated by Django 3.2.18 on 2026-01-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20260116_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='missedsale',
            name='price_per_stem',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potential price per stem', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='missedsale',
            name='stem_length_cm',
            field=models.PositiveIntegerField(default=0, help_text='Requested stem length'),
        ),
    ]
