# Generated by Django 3.2.18 on 2026-01-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20260116_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent_name',
            field=models.CharField(blank=True, default='TTC', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='awb_number',
            field=models.CharField(blank=True, help_text='Air Waybill Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_to',
            field=models.CharField(blank=True, help_text='Specific delivery location/person if different from Customer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='inco_term',
            field=models.CharField(blank=True, default='FOB', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_template',
            field=models.CharField(choices=[('default', 'Default Template'), ('awb', 'AWB / Export Template')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_of_transport',
            field=models.CharField(blank=True, default='AIR', max_length=50, null=True),
        ),
    ]
