# Generated by Django 3.2.18 on 2026-05-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20260125_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.PositiveIntegerField(help_text='Sequential box number within the order')),
                ('label', models.CharField(blank=True, help_text='Optional box label', max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_boxes', to='orders.order')),
            ],
            options={
                'ordering': ['box_number'],
                'unique_together': {('order', 'box_number')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='box',
            field=models.ForeignKey(blank=True, help_text='Physical box this item belongs to (for mixed boxes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.orderbox'),
        ),
    ]
