# Generated by Django 3.2.18 on 2025-08-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductprice',
            name='stem_length_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Stem length in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stem_length_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Stem length in centimeters', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customerproductprice',
            unique_together={('customer', 'product', 'stem_length_cm')},
        ),
    ]
