# Generated by Django 3.2.7 on 2025-08-12 00:28

from django.db import migrations

def populate_stem_lengths(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    CustomerProductPrice = apps.get_model('products', 'CustomerProductPrice')

    # Set default stem length for products
    for product in Product.objects.filter(stem_length_cm__isnull=True):
        product.stem_length_cm = 50  # Default 50cm
        product.save()

    # Set default stem length for customer product prices
    for price in CustomerProductPrice.objects.filter(stem_length_cm__isnull=True):
        price.stem_length_cm = 50  # Default 50cm
        price.save()

def reverse_populate_stem_lengths(apps, schema_editor):
    # No reverse operation needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250812_0017'),
    ]

    operations = [
        migrations.RunPython(populate_stem_lengths, reverse_populate_stem_lengths),
    ]
