# Generated by Django 3.2.7 on 2025-08-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250812_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stem_length_cm',
            field=models.PositiveIntegerField(help_text='Stem length in centimeters'),
        ),
        migrations.AlterField(
            model_name='customerproductprice',
            name='stem_length_cm',
            field=models.PositiveIntegerField(help_text='Stem length in centimeters'),
        ),
    ]
