# Generated by Django 3.2.18 on 2026-05-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250812_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_classification_code',
            field=models.CharField(blank=True, help_text='KRA Item Classification Code (if required)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_code',
            field=models.CharField(choices=[('A', '16%'), ('B', '8%'), ('C', '0% (Export/Zero-rated)'), ('D', 'Exempt'), ('E', '8%')], default='C', help_text='KRA Tax Code (usually C for export)', max_length=1),
        ),
    ]
