# Generated by Django 5.2 on 2025-04-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('preferred_currency', models.CharField(choices=[('KSH', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='customers.customer')),
            ],
        ),
    ]
