# Generated by Django 3.2.18 on 2026-01-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20251226_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_code_preference',
            field=models.CharField(choices=[('branch', 'Branch Short Code (Default)'), ('customer', 'Customer Short Code')], default='branch', help_text="Choose whether to use the Customer's short code or the Branch's short code for invoice numbering.", max_length=10),
        ),
    ]
