# Generated by Django 3.2.18 on 2026-01-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_invoice_code_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, help_text='Separate multiple emails with commas', max_length=500, null=True),
        ),
    ]
