# Generated by Django 3.2.18 on 2025-12-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_status_cbb790_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
    ]
