# Generated by Django 3.2.18 on 2025-07-27 10:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0007_auto_20250718_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('KSH', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], max_length=20)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_payments', to='customers.customer')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('per_order', 'Per Order Payment'), ('bulk', 'Bulk Payment'), ('monthly', 'Monthly Payment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('payment_created', 'Payment Created'), ('payment_updated', 'Payment Updated'), ('payment_cancelled', 'Payment Cancelled'), ('allocation_created', 'Allocation Created'), ('allocation_updated', 'Allocation Updated'), ('allocation_deleted', 'Allocation Deleted'), ('balance_recalculated', 'Balance Recalculated'), ('statement_generated', 'Statement Generated')], max_length=20)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(default='{}')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_payment_allocations', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymenttype'),
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(choices=[('KSH', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_orders', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_payments', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='account_statements_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_statements', to='customers.customer')),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['timestamp', 'action'], name='payments_pa_timesta_69aa0b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['customer', 'timestamp'], name='payments_pa_custome_fd60b4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment', 'order'], name='payments_pa_payment_07f53c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'order')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'payment_date'], name='payments_pa_custome_0a5e00_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_date'], name='payments_pa_status_3f89d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountstatement',
            unique_together={('customer', 'statement_date')},
        ),
    ]
