# Generated by Django 3.2.18 on 2025-12-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20250727_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='include_credits',
            field=models.BooleanField(default=True, help_text='Include credit notes in the statement'),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='include_payments',
            field=models.BooleanField(default=True, help_text='Include payments in the statement'),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='statement_type',
            field=models.CharField(choices=[('reconciliation', 'Reconciliation Statement'), ('periodic', 'Periodic Statement'), ('full_history', 'Full Account History')], default='reconciliation', max_length=20),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='total_claim_orders',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='total_paid_orders',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='total_partial_orders',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='total_pending_orders',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        # migrations.AlterUniqueTogether(
        #     name='accountstatement',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='paymentallocation',
        #     unique_together=set(),
        # ),
    ]
