# Generated by Django 3.2.18 on 2026-01-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20251226_1901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountstatement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together=set(),
        ),
    ]
