# Generated by Django 3.2.18 on 2026-03-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20260125_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
