# Generated by Django 3.2.18 on 2025-05-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
