# Generated by Django 3.2.18 on 2025-05-29 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
