# Generated by Django 3.2.18 on 2025-07-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20250529_2101'),
        ('invoices', '0005_auto_20250529_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='order_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='orders.orderitem'),
            preserve_default=False,
        ),
    ]
