# Generated by Django 3.2.18 on 2025-07-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20250529_2101'),
        ('invoices', '0006_creditnote_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='orders.orderitem'),
        ),
    ]
