# Generated by Django 3.2.18 on 2025-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_creditnote_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='account_statements_pdfs/'),
        ),
    ]
