# Generated by Django 3.2.18 on 2025-07-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20250718_2237'),
        ('invoices', '0008_accountstatement_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='stems_affected',
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stems_affected', models.PositiveIntegerField()),
                ('credit_amount', models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=12)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_items', to='invoices.creditnote')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='creditnote',
            name='order_items',
            field=models.ManyToManyField(related_name='credit_notes', through='invoices.CreditNoteItem', to='orders.OrderItem'),
        ),
    ]
