# Generated by Django 3.2.18 on 2025-07-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_payment_paymentallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentallocation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentAllocation',
        ),
    ]
