# Generated by Django 3.2.18 on 2025-08-30 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20250812_2242'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0011_auto_20250727_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountstatement',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='creditnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='order_items',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='credit_type',
            field=models.CharField(choices=[('order_reduction', 'Order Total Reduction'), ('customer_credit', 'Customer Credit Balance')], default='order_reduction', max_length=20),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='currency',
            field=models.CharField(choices=[('KSH', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], default='KSH', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='total_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='reason',
            field=models.CharField(blank=True, help_text='Specific reason for this item credit', max_length=255),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.TextField(help_text='Reason/issue for the credit note (e.g., damaged items, quality issues, short delivery)'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_items', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='stems_affected',
            field=models.PositiveIntegerField(help_text='Number of stems to credit'),
        ),
        migrations.AlterUniqueTogether(
            name='creditnoteitem',
            unique_together={('credit_note', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['order', 'status'], name='invoices_cr_order_i_727e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['created_at'], name='invoices_cr_created_a35705_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['currency'], name='invoices_cr_currenc_2e0ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnoteitem',
            index=models.Index(fields=['credit_note', 'order_item'], name='invoices_cr_credit__235793_idx'),
        ),
        migrations.DeleteModel(
            name='AccountStatement',
        ),
    ]
