# Generated by Django 3.2.18 on 2025-08-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20250830_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='total_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
