# Generated by Django 3.2.18 on 2025-12-26 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_auto_20250812_2242'),
        ('invoices', '0013_auto_20250830_2101'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='creditnote',
            name='invoices_cr_order_i_727e1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditnote',
            name='invoices_cr_created_a35705_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditnote',
            name='invoices_cr_currenc_2e0ed0_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditnoteitem',
            name='invoices_cr_credit__235793_idx',
        ),
        migrations.RenameField(
            model_name='creditnote',
            old_name='applied_at',
            new_name='approved_at',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='credit_type',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='order',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='title',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='total_credit_amount',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credit amount for this line', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='stems',
            field=models.PositiveIntegerField(default=0, help_text='Number of stems credited'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='currency',
            field=models.CharField(choices=[('KSH', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.TextField(help_text='Reason for the credit note'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(choices=[('pending', 'Draft / Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.creditnote'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_items', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='creditnoteitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='creditnoteitem',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='creditnoteitem',
            name='stems_affected',
        ),
    ]
