# Generated by Django 3.2.18 on 2026-05-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_auto_20251226_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETIMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kra_pin', models.CharField(help_text='Your KRA PIN', max_length=20)),
                ('branch_id', models.CharField(help_text='eTIMS Branch ID', max_length=10)),
                ('device_serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('api_base_url', models.URLField(help_text='eTIMS API Base URL (Sandbox or Production)')),
                ('certificate_path', models.CharField(blank=True, help_text='Path to digital certificate if required', max_length=255, null=True)),
                ('certificate_password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'eTIMS Settings',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='etims_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='etims_internal_data',
            field=models.CharField(blank=True, help_text='KRA Internal Data (Control Code)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='etims_qr_code_url',
            field=models.URLField(blank=True, help_text='KRA QR Code URL', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='etims_receipt_number',
            field=models.CharField(blank=True, help_text='KRA eTIMS Receipt Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='etims_signature',
            field=models.CharField(blank=True, help_text='KRA eTIMS Signature', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='etims_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
