# Generated by Django 3.2.18 on 2026-01-25 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(help_text='Email address for sending', max_length=255)),
                ('smtp_password', models.CharField(help_text='App Password or Email Password', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_user', models.CharField(help_text='Email address for reading (usually same as smtp_user)', max_length=255)),
                ('imap_password', models.CharField(help_text='Usually same as smtp_password', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
