# Generated by Django 3.2.18 on 2026-01-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='imap_host',
            field=models.CharField(default='mail.zaharaflowers.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='imap_password',
            field=models.CharField(default='Lucy@ZaharaLTD?', help_text='Usually same as smtp_password', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='imap_user',
            field=models.CharField(default='lucy@zaharaflowers.com', help_text='Email address for reading (usually same as smtp_user)', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_host',
            field=models.CharField(default='mail.zaharaflowers.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_password',
            field=models.CharField(default='Lucy@ZaharaLTD?', help_text='App Password or Email Password', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_port',
            field=models.PositiveIntegerField(default=465),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_user',
            field=models.CharField(default='lucy@zaharaflowers.com', help_text='Email address for sending', max_length=255),
        ),
    ]
